In [1]:
import numpy as np

In [2]:
numpy_arr = np.zeros(shape=(5,5))

In [3]:
print(numpy_arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [5]:
numpy_arr[:,:] = 10

In [6]:
print(numpy_arr)

[[10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10.]]


In [7]:
arr = np.ones(shape=(5,5))

In [8]:
arr = arr * 10;

In [9]:
print(arr)

[[10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10.]]
